[package]
name = "pong"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
dns-lookup = "2.0.4"
ping = "0.6.1"
tokio-cron-scheduler = "0.14.0"
tokio = { version = "1.47.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
log = "0.4.27"
env_logger = "0.11.8"
chrono = "0.4.41"
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34-deprecated"
prometheus = "0.14.0"
clap = { version = "4.5.42", features = ["derive"] }
strum_macros = "0.27.2"
